### PR TITLE
Make it easier to apply the "example" RBAC resources

### PR DESCRIPTION
**Pull request by hoegaarden**
By not hardcoding the namespace in these object, we can use these RBAC
objects and apply the to differently named namespaces easily.

### CODE REVIEW

**Comment by Samze** [comment]
Is there any reason not to remove the namespace from the PackageInstall.yaml too?

We should also make this same change to the Amazon RDS example sa.yaml/packageinstall.yaml

**Review by Samze — COMMENTED** [review]
Makes sense to me.

Is there any reason not to remove the namespace from the [PackageInstall](https://github.com/vmware-tanzu/tanzu-application-platform-reference-service-packages/blob/main/google/config-connector/cloudsql/package-install.yaml) too?

We should also make this same change to the Amazon RDS example [here](https://github.com/vmware-tanzu/tanzu-application-platform-reference-service-packages/tree/main/amazon/ack/rds).

**Comment by hoegaarden** [comment]
> Is there any reason not to remove the namespace from the [PackageInstall](https://github.com/vmware-tanzu/tanzu-application-platform-reference-service-packages/blob/main/google/config-connector/cloudsql/package-install.yaml) too?

That's just an oversight on my side, I'll remove the namespace in the PackageInstall to, also for the RDS things.

**Comment by hoegaarden** [comment]
Removed all namespaces. Also opportunistically snuck in a file rename (`sa.yaml` => `rbac.yaml`) which I think makes a bit more sense. If not, happy to drop that commit.

/ptal

**Review by Samze — APPROVED** [review]
LGTM

**Pull request merged**
